version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    environment:
      ENV: ${ENV:-demo}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthz', timeout=2)"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE_URL: /api
    # optional: hot-reload nginx.conf without rebuilding
    # volumes:
    #   - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8080:80"   # public port → Nginx → frontend; proxies /api to FastAPI
    restart: unless-stopped
